/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { EthSender, EthSenderInterface } from "../EthSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class EthSender__factory {
  static readonly abi = _abi;
  static createInterface(): EthSenderInterface {
    return new utils.Interface(_abi) as EthSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthSender {
    return new Contract(address, _abi, signerOrProvider) as EthSender;
  }
}
