/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type WithdrawalTicketStruct = {
  value: BigNumberish;
  nonce: BigNumberish;
  receiver: string;
  sender: string;
  escrowHash: BytesLike;
  token: string;
};

export type WithdrawalTicketStructOutput = [
  BigNumber,
  BigNumber,
  string,
  string,
  string,
  string
] & {
  value: BigNumber;
  nonce: BigNumber;
  receiver: string;
  sender: string;
  escrowHash: string;
  token: string;
};

export type SignatureStruct = { r: BytesLike; s: BytesLike; v: BigNumberish };

export type SignatureStructOutput = [string, string, number] & {
  r: string;
  s: string;
  v: number;
};

export interface L1ContractInterface extends utils.Interface {
  functions: {
    "claimTicket((uint256,uint256,address,address,bytes32,address),bytes32,(bytes32,bytes32,uint8))": FunctionFragment;
    "claimTickets((uint256,uint256,address,address,bytes32,address)[],bytes32[],(bytes32,bytes32,uint8)[])": FunctionFragment;
    "depositEth()": FunctionFragment;
    "depositToken(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimTicket",
    values: [WithdrawalTicketStruct, BytesLike, SignatureStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTickets",
    values: [WithdrawalTicketStruct[], BytesLike[], SignatureStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositEth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface L1Contract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L1ContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimTicket(
      ticket: WithdrawalTicketStruct,
      escrowPreimage: BytesLike,
      signature: SignatureStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTickets(
      tickets: WithdrawalTicketStruct[],
      escrowPreimages: BytesLike[],
      signatures: SignatureStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositEth(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimTicket(
    ticket: WithdrawalTicketStruct,
    escrowPreimage: BytesLike,
    signature: SignatureStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTickets(
    tickets: WithdrawalTicketStruct[],
    escrowPreimages: BytesLike[],
    signatures: SignatureStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositEth(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositToken(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimTicket(
      ticket: WithdrawalTicketStruct,
      escrowPreimage: BytesLike,
      signature: SignatureStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTickets(
      tickets: WithdrawalTicketStruct[],
      escrowPreimages: BytesLike[],
      signatures: SignatureStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    depositEth(overrides?: CallOverrides): Promise<void>;

    depositToken(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimTicket(
      ticket: WithdrawalTicketStruct,
      escrowPreimage: BytesLike,
      signature: SignatureStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTickets(
      tickets: WithdrawalTicketStruct[],
      escrowPreimages: BytesLike[],
      signatures: SignatureStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositEth(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimTicket(
      ticket: WithdrawalTicketStruct,
      escrowPreimage: BytesLike,
      signature: SignatureStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTickets(
      tickets: WithdrawalTicketStruct[],
      escrowPreimages: BytesLike[],
      signatures: SignatureStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositEth(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
