/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type SignatureStruct = { r: BytesLike; s: BytesLike; v: BigNumberish };

export type SignatureStructOutput = [string, string, number] & {
  r: string;
  s: string;
  v: number;
};

export interface SignatureCheckerInterface extends utils.Interface {
  functions: {
    "recoverSigner(bytes32,(bytes32,bytes32,uint8))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "recoverSigner",
    values: [BytesLike, SignatureStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "recoverSigner",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SignatureChecker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SignatureCheckerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    recoverSigner(
      hash: BytesLike,
      signature: SignatureStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  recoverSigner(
    hash: BytesLike,
    signature: SignatureStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    recoverSigner(
      hash: BytesLike,
      signature: SignatureStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    recoverSigner(
      hash: BytesLike,
      signature: SignatureStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    recoverSigner(
      hash: BytesLike,
      signature: SignatureStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
